const recipes =[

		{ "id": 1,
		"name":"Jollof Rice","owner": "tracy",
    "timetaken":"30 min",
		 "ingredient": ["rice", "palm oil", "tomatoes", "onions", "bay leaves"],
 		 "equippments":["gas cooker", "knife","blender", "cutter"],
      "steps":"not yet ready",
 		 "upvotes": 300,
      "downvotes": 30,
		 "favourite": true,
 		 "reviews": []},

		{	"id": 2,
			"name":"Shawama","owner": "marley",
       "timetaken":"1800s",
            "ingredient": ["shawama bread", "chiken", "hot dog", "onions", "bay leaves"],
            "equippments":["gas cooker", "knife","blender", "cutter"],
            "steps":"not yet ready",
            "upvotes": 300,
            "downvotes": 30,
            "favourite": false,
            "reviews": [ ]},

            {
            	"id": 3,
            	"name":"Chiken Source", "owner": "cherry",
            "timetaken":"70min",
            "ingredient": ["grilled chiken", "palm oil", "tomatoes", "onions", "bay pepe"],
            "equipments":["gas cooker", "knife","blender", "cutter"],
             "steps":"not yet ready",
            "upvotes": 300,
            "downvotes": 30,
            "favourite": true,
            "reviews": [] },


            {	"id": 4,
            	"name":"cylinda Rice", "owner": "justos",
            "timetaken":"1/2 hr",
            "ingredient": ["rice", "curry", "tomatoes", "onions", "bay leaves"],
            "equippments":["gas cooker", "knife","blender", "cutter"],
             "steps":"not yet ready",
            "upvote": 1000,
            "downvote": 30,
            "favouriteCount":0,
            "favourite": false,
            "reviews": [],
          },

          { "id": 5,
		"name":"KoKo yam Vegetables","owner": "Blessing",
    "timetaken":"30 min",
		 "ingredient": ["rice", "palm oil", "kokoYam", "onions", "salt", "pepe"],
 		 "equippments":["gas cooker", "knife","blender", "cutter"],
 		  "steps":"not yet ready",
      "upvotes": 210,
      "downvotes": 30,
      "favouriteCount":200,
		 "favourites": true,
 		 "reviews": []},

		{	"id": 6,
			"name":"Shawama","owner": "Victoria",
       "timetaken":"1800s",
            "ingredient": ["shawama bread", "chiken", "hot dog", "onions", "bay leaves"],
            "equippments":["gas cooker", "knife","blender", "cutter"],
            "steps":"not yet ready",
            "upvotes": 350,
            "downvotes": 30,
             "favouriteCount":24,
            "favourite": false,
            "reviews": [ ]},

            {
            	"id": 7,
            	"name":"Chiken Source", "owner": "justin",
            "timetaken":"70min",
            "ingredient": ["rice", "palm oil", "tomatoes", "onions", "bay pepe"],
            "equipments":["gas cooker", "knife","blender", "cutter"],
            "upvotes": 300,
             "steps":"not yet ready",
            "downvotes": 30,
             "favouriteCount":25,
            "favourite": true,
            "reviews": [] },


            {	"id": 8,
            	"name":"Chinese Roll", "owner": "Idris",
            "timetaken":"1/2 hr",
            "ingredient": ["flow", "palm oil", "tomatoes", "onions", "chiken", "mozzarella cheese"],
            "equippments":["gas cooker", "knife","blender", "cutter"],
             "steps":"not yet ready",
            "upvotes": 1000,
            "downvotes": 30,
            "favouriteCount":26,
            "favourite": false,
            "reviews": [] 
          },
          
          {
            	"id": 9,
            	"name":"Chiken Source", "owner": "justin",
            "timetaken":"70min",
            "ingredient": ["rice", "palm oil", "tomatoes", "onions", "bay pepe"],
            "equipments":["gas cooker", "knife","blender", "cutter"],
             "steps":"not yet ready",
            "upvotes": 300,
            "downvotes": 30,
             "favouriteCount":25,
            "favourite": true,
            "reviews": [] },


            {	"id": 10,
            	"name":"Chinese Roll", "owner": "Idris",
            "timetaken":"1/2 hr",
            "ingredient": ["flow", "palm oil", "tomatoes", "onions", "chiken", "mozzarella cheese"],
            "equippments":["gas cooker", "knife","blender", "cutter"],
             "steps":"not yet ready",
            "upvotes": 1000,
            "downvotes": 30,
            "favouriteCount":26,
            "favourite": false,
            "reviews": [] 
          },
          
          

]

export default recipes;